### ISSUE TITLE
export_Pptx()

### ISSUE THREAD

**Issue by velpulagopiraju** [ansys/pydynamicreporting#112]
### 📝 Description of the feature

is it possible to export report in .Pptx format. i just seen only export_pdf() and export_html() commands only in Api references page.

**Comment by raj366v** [comment]
@margalva, @RobPasMue, @PipKat can i get any suggestion on this.

**Comment by margalva** [comment]
@raj366v the PPTX export feature is ADR works quite differently, as you need to set up the input PPTX layout file with placeholders for where you'd like the information to go.
So you need to create a report with PPTX Layout as the top template, and then simply call that report to have the PPTX file created and downloaded on your machine.
For more info, see here:

https://nexusdemo.ensight.com/docs/en/html/PPTX.html#

**Comment by raj366v** [comment]
Hi @margalva Thank you for your quick update.
