### ISSUE TITLE
Support NumPy 2.X

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pydynamicreporting#173]
Hi @margalva @mariostieriansys @viseshrp 

Looks like ansys-dynamicreporting-core is preventing the usage of NumPy 2.x across the rest of the ecosystem:

https://github.com/ansys/pydynamicreporting/blob/8f9f78d7ad80a85deaab6db9f528e750d85f30a7/pyproject.toml#L53

Is there a reason for this? If not, can we remove the upper limit? Proposing according PR...

**Comment by RobPasMue** [comment]
See https://github.com/ansys/pydynamicreporting/pull/174

**Comment by margalva** [comment]
@RobPasMue yes, there is a reason for this. pydynamicreporting is pulled in EnSight as it uses it for its report generation. EnSight is not compatible with numpy >= 2. Therefore, pydynamicreporting cannot update its numpy dependency.

**Comment by RobPasMue** [comment]
Okay, thanks for the explanation @margalva - this might become a problem for the rest of the ecosystem, especially for the PyAnsys metapackage. Currently, it would cause incompatibilities with other packages. I just had a look and it does seem like PyEnSight is using numpy<2. @mariostieriansys @randallfrank is this something we can solve?

https://github.com/ansys/pyensight/blob/260f5b8e6055782903343bfe87e0a2b75290f654/pyproject.toml#L34

Pinging @ansys/pyansys-core since the entire ecosystem is impacted.

**Comment by RobPasMue** [comment]
> pydynamicreporting is pulled in EnSight as it uses it for its report generation. EnSight is not compatible with numpy >= 2. Therefore, pydynamicreporting cannot update its numpy dependency.

Some additional info... EnSight should be the one preventing the installation of NumPy 2.X IMO.

If your package is not the one limited by NumPy, you shouldn't be defining the upper limit for it. EnSight should be the one limiting that version instead. That would prevent you from having to change this upper limit in N repos rather than just changing it on the only affected repo (EnSight). In fact, I would recommend to support NumPy 1.X and 2.X on your side and if EnSight only supports 1.X then that's fine - but let EnSight limit the version used.
