### ISSUE TITLE
Docs Banner invisible in "light" mode due to contrast

### ISSUE THREAD

**Issue by jgd10** [ansys/pydynamicreporting#182]
### Description of the modifications

When in "light" mode in the documentation, the banner menu buttons are black text on black background and thus invisible.

![Image](https://github.com/user-attachments/assets/c21b3d38-80f6-4df4-87a5-56580e581e4c)

![Image](https://github.com/user-attachments/assets/0b5694d8-a879-4020-ab97-105c2d563226)

**Comment by margalva** [comment]
This has been fixed with release 0.9.0:

https://dynamicreporting.docs.pyansys.com/version/stable/index.html
