### ISSUE TITLE
Bug located in utils/report_objects.py TemplateRest object: params field and get_params() method inconsistency

### ISSUE THREAD

**Issue by zhang-yuanrui** [ansys/pydynamicreporting#193]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

In the [documentation](https://dynamicreporting.docs.pyansys.com/version/stable/lowlevelapi/TemplateObjects.html#data-members): 
`params - A Python dictionary of the parameters for this specific report_type. You can also access the parameters via the method [get_params()](https://dynamicreporting.docs.pyansys.com/version/stable/lowlevelapi/TemplateObjects.html#template-get-params).`
However, template.params returns a string because in the source code, self.params is assigned by `json.dumps`. On the other hand, get_params() method returns a python dictionary as expected because it returns `json.loads(self.params)`
@viseshrp @margalva do we want this different behavior between these 2 accesses?

### 📝 Steps to reproduce

As described

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
N/A
```

**Comment by viseshrp** [comment]
I think it is intentional. params returns the direct attribute with no conversion. get_params loads the str as json. I would just leave it  as is for backwards compatibility. It does not confuse me, but maybe I am just used to seeing it. If you feel it is confusing, feel free to add a new method.

**Comment by margalva** [comment]
@zhang-yuanrui I agree with Visesh - the "params" gives you access directly to the attribute, and it's not supposed to be the way the user access it. get_params is the recommended way to access it - and that's why it does the conversion for you.
I guess it's not consistent, but "params" isn't supposed to be used directly.
