### ISSUE TITLE
Installation of structures bundle does not include CEI/Nexus needed to run pydynamicreporting

### ISSUE THREAD

**Issue by ekostson** [ansys/pydynamicreporting#63]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When a user does an Installation of Ansys structural bundle (so WB/APDL,etc.) only, then this does not include or create CEI folder and Nexus files needed to run pydynamicreporting.

Ideally we would need to include the CEI folder and Nexus files when installing only the structural bundle, just as it is probably done when installing the Fluids bundle (have in mind that structural engineers will not of course often install Fluid bundles due to various reasons so we would need to create the folders and Nexus files with the structures Ansys installation and any other installations).

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023 R2

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
p
```

**Comment by margalva** [comment]
You are correct.

In 2023 R2, Nexus (the "old" name for Ansys Dynamic Reporting") can only be installed as part of the EnSight package, which is under the Fluid section.

In 2024 R1, we have added an entry in the Ansys installer for ADR specifically, so you can explicitly request for the CEI/ folder to be installed as part of your installation. At the moment (aka, for 24R1), this will still be visible only under the Fluids package, so you will need to actively go there during the installation process and toggle on the "Dynamic Reporting" entry, even if you're only installing structure. But we're looking into the possibility of moving this installation toggle in an other area outside of Fluids (maybe a 'Common / Shared package' area?) for 2024 R2, but this is too early to say what the decision will be.

Anyway, I've added comments to clarify this aspect of the installation in the pydynamicreporting docs - see PR 67.

Thank you for bring up the issue, which allowed us to start the conversation.
